// PMD axis initialization source code generated by Pro-Motion version 5.60  
//
// Compatible with C-Motion version 5.7
//

#include "C-Motion.h"
#include "PMDdiag.h"
#include "PMDsys.h"
#include "PMDutil.h"

// N-Series ION DD481S0056/06
PMDresult SetupAxis1(PMDAxisHandle* phAxis)
{
PMDresult result = PMD_NOERROR;

  PMD_RESULT(PMDSetSampleTime (phAxis, 51))
  PMD_RESULT(PMDSetMotorType (phAxis, 3))
  PMD_RESULT(PMDResetEventStatus (phAxis, 0x0000))
  PMD_RESULT(PMDSetCommutationParameter (phAxis, PMDCommutationParameterPhaseCounts, 256))
  PMD_RESULT(PMDSetProfileMode (phAxis, 1))
  PMD_RESULT(PMDSetPositionErrorLimit (phAxis, 65535))
  PMD_RESULT(PMDSetSettleTime (phAxis, 0))
  PMD_RESULT(PMDSetSettleWindow (phAxis, 0))
  PMD_RESULT(PMDSetTrackingWindow (phAxis, 0))
  PMD_RESULT(PMDSetActualPositionUnits (phAxis, 1))
  PMD_RESULT(PMDSetEncoderSource (phAxis, 2))
  PMD_RESULT(PMDSetEncoderToStepRatio (phAxis, 4096, 6400))
  PMD_RESULT(PMDSetGearMaster (phAxis, 0, 0))
  PMD_RESULT(PMDSetMotorCommand (phAxis, 5457))
  PMD_RESULT(PMDSetMotionCompleteMode (phAxis, 0))
  PMD_RESULT(PMDSetSignalSense (phAxis, 0x0004))
  PMD_RESULT(PMDSetCaptureSource (phAxis, 1))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 0x0000, 0x00000000))
  PMD_RESULT(PMDSetBreakpointValue (phAxis, 0x0001, 0x00000000))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 0x0000, 0, 0, 0))
  PMD_RESULT(PMDSetBreakpoint (phAxis, 0x0001, 0, 0, 0))
  PMD_RESULT(PMDSetCurrentControlMode (phAxis, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 0, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 1, 0))
  PMD_RESULT(PMDSetFOC (phAxis, 2, 2, 32767))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 0, 1300))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 1, 600))
  PMD_RESULT(PMDSetCurrentLoop (phAxis, 2, 2, 16000))
  PMD_RESULT(PMDSetCurrent (phAxis, PMDCurrentHoldingMotorLimit, 2729))
  PMD_RESULT(PMDSetCurrent (phAxis, PMDCurrentHoldingDelay, 11765))
  PMD_RESULT(PMDSetAxisOutMask (phAxis, 0, 0, 0x0001, 0x0000))
  PMD_RESULT(PMDSetFaultOutMask (phAxis, 0x0600))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterOvervoltageLimit, 6000))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterUndervoltageLimit, 1000))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, PMDCurrentFoldbackContinuousCurrentLimit, 9650))
  PMD_RESULT(PMDSetCurrentFoldback (phAxis, PMDCurrentFoldbackI2tEnergyLimit, 478))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventPositiveLimit, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventNegativeLimit, 0x0008))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventMotionError, 0x0000))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventCurrentFoldback, 0x0007))
  PMD_RESULT(PMDSetDrivePWM (phAxis, PMDDrivePWMLimit, 16384))
  PMD_RESULT(PMDSetDrivePWM (phAxis, PMDDrivePWMFrequency, 5000))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterTemperatureLimit, 19200))
  PMD_RESULT(PMDSetDriveFaultParameter (phAxis, PMDDriveFaultParameterTemperatureHysteresis, 1280))
  PMD_RESULT(PMDSetEventAction (phAxis, PMDEventActionEventBrakeAsserted, 0x000a))
  PMD_RESULT(PMDUpdate (phAxis))
  PMD_RESULT(PMDSetOperatingMode (phAxis, 0x0027))
  PMD_RESULT(PMDSetGearRatio (phAxis, 0x00000000))
  PMD_RESULT(PMDSetMotorCommand (phAxis, 5457))
  PMD_RESULT(PMDUpdate (phAxis))

  return result;
}

PMDresult SetupAxis2(PMDAxisHandle* phAxis)
{
PMDresult result = PMD_NOERROR;

  PMD_RESULT(PMDSetEncoderSource (phAxis, 0))
  PMD_RESULT(PMDSetSignalSense (phAxis, 0x0000))

  return result;
}


#